version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: django_mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: django_web_app
    command: python root/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8082:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=django_db
      - DB_USER=django_user
      - DB_PASSWORD=django_password

volumes:
  mysql_data:
