# Generated by Django 4.2.29 on 2026-04-03 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0001_initial'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('office_type', models.CharField(choices=[('headquarters', 'Headquarters'), ('regional', 'Regional Office'), ('branch', 'Branch Office'), ('remote_hub', 'Remote Hub')], max_length=20)),
                ('full_address', models.TextField(blank=True)),
                ('local_currency', models.CharField(choices=[('BDT', 'BDT'), ('USD', 'USD'), ('GBP', 'GBP'), ('AED', 'AED'), ('INR', 'INR')], default='BDT', max_length=10)),
                ('timezone', models.CharField(choices=[('Asia/Dhaka', 'Asia/Dhaka (UTC+6)'), ('Europe/London', 'Europe/London (UTC+0/+1)'), ('Asia/Dubai', 'Asia/Dubai (UTC+4)'), ('America/New_York', 'America/New_York (UTC-5/-4)')], default='Asia/Dhaka', max_length=50)),
                ('tax_law', models.CharField(blank=True, max_length=200)),
                ('labor_law', models.CharField(blank=True, max_length=200)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Max headcount')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('planned', 'Planned')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hr_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_contact_offices', to='core_module.employee')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
