# Generated by Django 4.2.29 on 2026-09-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('late', 'Late'), ('on_leave', 'On Leave'), ('work_from_home', 'Work From Home')], db_index=True, default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='current_stage',
            field=models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected')], db_index=True, default='applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('probation', 'Probation'), ('resigned', 'Resigned'), ('terminated', 'Terminated')], db_index=True, default='probation', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='from_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='to_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pay_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pay_period',
            field=models.CharField(db_index=True, help_text='e.g., January 2026', max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'status'], name='core_module_date_215c4b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'date'], name='core_module_employe_a30efd_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status', 'join_date'], name='core_module_status_9d2038_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'status'], name='core_module_departm_ee1809_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'status'], name='core_module_employe_444cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status', 'from_date'], name='core_module_status_e47633_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['pay_period', 'pay_date'], name='core_module_pay_per_8477af_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['employee', 'pay_period'], name='core_module_employe_fec321_idx'),
        ),
    ]
