"""
Training Validation Constants
"""

# Validation Rules
MIN_TRAINING_DURATION_HOURS = 0.5
MAX_TRAINING_DURATION_HOURS = 1000
MIN_PARTICIPANTS = 1
MAX_PARTICIPANTS = 500
TRAINING_COMPLETION_PERCENTAGE = 80
CERTIFICATE_VALIDITY_MONTHS = 12
