"""
Recruitment Validation Constants
"""

# Validation Rules
MIN_EXPERIENCE_YEARS = 0
MAX_EXPERIENCE_YEARS = 60
MIN_JOB_TITLE_LENGTH = 3
MAX_JOB_TITLE_LENGTH = 100
MAX_APPLICATIONS_PER_CANDIDATE = 10
