# Generated by Django 4.2.29 on 2026-04-02 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_anonymous', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('management', 'Management'), ('compliance', 'Compliance'), ('technical', 'Technical'), ('soft_skills', 'Soft Skills'), ('safety', 'Safety'), ('onboarding', 'Onboarding'), ('leadership', 'Leadership')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('duration_hours', models.PositiveIntegerField(default=1)),
                ('instructor', models.CharField(blank=True, max_length=100)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['course_name'],
            },
        ),
        migrations.CreateModel(
            name='TalentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_role', models.CharField(max_length=100)),
                ('potential', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('performance_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Current performance rating', max_digits=3, null=True)),
                ('readiness', models.CharField(choices=[('ready_now', 'Ready Now'), ('1_year', '1 Year'), ('2_years', '2 Years'), ('3_plus_years', '3+ Years'), ('not_ready', 'Not Ready')], max_length=20)),
                ('next_role', models.CharField(blank=True, max_length=100)),
                ('development_areas', models.TextField(blank=True)),
                ('key_strengths', models.TextField(blank=True)),
                ('succession_plan', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talent_profile', to='core_module.employee')),
            ],
            options={
                'ordering': ['-potential', '-performance_rating'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='core_module.employee')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='talent_growth.engagementsurvey')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('rating', 'Rating Scale'), ('text', 'Text Response'), ('multiple_choice', 'Multiple Choice')], max_length=20)),
                ('options', models.TextField(blank=True, help_text='Comma-separated options for multiple choice')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='talent_growth.engagementsurvey')),
            ],
            options={
                'ordering': ['survey', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SuccessionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('readiness_level', models.CharField(max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_module.department')),
                ('primary_successor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_succession', to='core_module.employee')),
                ('secondary_successors', models.ManyToManyField(blank=True, related_name='secondary_successions', to='core_module.employee')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognition_type', models.CharField(choices=[('kudos', 'Kudos'), ('peer_award', 'Peer Award'), ('innovation', 'Innovation Award'), ('team_player', 'Team Player'), ('leader', 'Leader Award')], max_length=20)),
                ('reason', models.TextField()),
                ('points', models.PositiveIntegerField(default=0)),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions', to='core_module.employee')),
                ('recognized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_recognitions', to='core_module.employee')),
            ],
            options={
                'ordering': ['-given_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_period', models.CharField(help_text='e.g., Q4 2025', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Rating out of 5', max_digits=3, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('employee_comments', models.TextField(blank=True)),
                ('reviewer_comments', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_module.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='core_module.employee')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_reviews', to='core_module.employee')),
            ],
            options={
                'verbose_name': 'Performance Review',
                'verbose_name_plural': 'Performance Reviews',
                'ordering': ['-review_period'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=200)),
                ('target', models.TextField()),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Score percentage', max_digits=5, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight for calculation', max_digits=3)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='talent_growth.performancereview')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_started', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core_module.employee')),
                ('parent_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_goals', to='talent_growth.goal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='enrolled', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Completion score percentage', max_digits=5, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='training/certificates/')),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='talent_growth.trainingcourse')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='core_module.employee')),
            ],
            options={
                'ordering': ['-enrollment_date'],
                'unique_together': {('employee', 'course')},
            },
        ),
    ]
